# Generated by Django 3.2.5 on 2021-07-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
