# Generated by Django 3.2.5 on 2021-07-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_application', '0003_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
