# Generated by Django 3.2.5 on 2021-07-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_application', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
